# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

name: CI

env:
  CI: true

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: ^7.1.5

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-08-12
          profile: minimal

      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Run unit tests
        run: pnpm test:unit

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: ^7.1.5

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-08-12
          profile: minimal

      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Run e2e tests
        run: pnpm test:e2e

  unit-test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: ^7.1.5

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-08-12
          profile: minimal

      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Run unit tests
        run: pnpm test:unit

  e2e-test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: ^7.1.5

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-08-12
          profile: minimal

      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Run e2e tests
        run: pnpm test:e2e
