# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize]

name: Build, test

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        CI: true
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2021-08-12
        profile: minimal

    - run: yarn install --pure-lockfile
    - run: yarn build
    - run: yarn test

