# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  push:
    branches:
      - master

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install pnpm
      uses: pnpm/action-setup@v2.1.0
      with:
        version: 6.0.2

    - name: Pnpm install
      run: pnpm install

    - name: Create Release Pull Request
      uses: changesets/action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
