name: release-tag

on:
  push:
    tags:
      - v* # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: ^7.1.5

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create and publish versions
        uses: changesets/action@v1
        with:
          publish: pnpm publish -r --access public
          tag_name: ${{ github.ref }}
