on:
  push:
    branches: [dev]
#    paths:
#      - "packages/toolpack/scripts/version.js"
  pull_request:
    types: [opened, synchronize]

name: SWC build, test, and deploy

jobs:
  testsPass:
    name: Exit When Test Failed
    runs-on: ubuntu-latest
    needs:
      [
        testUnit
      ]
    steps:
      - run: exit 0


  testUnit:
    name: Unit Test SWC Native Code
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 25
      - run: echo ::set-output name=DOCS_CHANGE::$(node skip-docs-change.js echo 'not-docs-only-change')
        id: docs-change
      - name: Install
        if: ${{ steps.docs-change.outputs.DOCS_CHANGE != 'docs only change' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-08-12
          profile: minimal
      - run: cd packages/toolpack/src/swc && cargo test
        if: ${{ steps.docs-change.outputs.DOCS_CHANGE != 'docs only change' }}

  # Build binaries for publishing
  buildNative:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: 'x86_64-apple-darwin'
            build: |
              npm i -g @napi-rs/cli@1.2.1 turbo@1.0.28
              turbo run build-native --cache-dir=".turbo" -- --release
              strip -x packages/toolpack/swc-source/native/shuvi-swc.*.node
          - host: windows-latest
            build: |
              npm i -g @napi-rs/cli@1.2.1 turbo@1.0.28
              turbo run build-native --cache-dir=".turbo" -- --release
            target: 'x86_64-pc-windows-msvc'
          - host: windows-latest
            build: |
              npm i -g @napi-rs/cli@1.2.1 turbo@1.0.28
              turbo run build-native --cache-dir=".turbo" -- --release --target i686-pc-windows-msvc
            target: 'i686-pc-windows-msvc'
          - host: ubuntu-latest
            target: 'x86_64-unknown-linux-gnu'
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine-zig
            # Node.js in Baidu need to compatible with `GLIBC_2.12`
            build: >-
              set -e &&
              rustup toolchain install nightly-2021-08-12 &&
              rustup default nightly-2021-08-12 &&
              rustup target add x86_64-unknown-linux-gnu &&
              npm i -g @napi-rs/cli@1.2.1 turbo@1.0.28 &&
              turbo run build-native --cache-dir=".turbo" -- --release --target x86_64-unknown-linux-gnu --zig --zig-abi-suffix 2.12 &&
              llvm-strip -x packages/toolpack/swc-source/native/shuvi-swc.*.node
          - host: ubuntu-latest
            target: 'x86_64-unknown-linux-musl'
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
            build: >-
              set -e &&
              rustup toolchain install nightly-2021-08-12 &&
              rustup default nightly-2021-08-12 &&
              rustup target add x86_64-unknown-linux-musl &&
              npm i -g @napi-rs/cli@1.2.1 turbo@1.0.28 &&
              turbo run build-native --cache-dir=".turbo" -- --release --target x86_64-unknown-linux-musl &&
              strip packages/toolpack/swc-source/native/shuvi-swc.*.node
          - host: macos-latest
            target: 'aarch64-apple-darwin'
            build: |
              sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*;
              export CC=$(xcrun -f clang);
              export CXX=$(xcrun -f clang++);
              SYSROOT=$(xcrun --sdk macosx --show-sdk-path);
              export CFLAGS="-isysroot $SYSROOT -isystem $SYSROOT";
              npm i -g @napi-rs/cli@1.2.1 turbo@1.0.28 &&
              turbo run build-native --cache-dir=".turbo" -- --release --target aarch64-apple-darwin
              strip -x packages/toolpack/swc-source/native/shuvi-swc.*.node
          - host: ubuntu-latest
            target: 'aarch64-unknown-linux-gnu'
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine-zig
            build: >-
              set -e &&
              rustup toolchain install nightly-2021-08-12 &&
              rustup default nightly-2021-08-12 &&
              rustup target add aarch64-unknown-linux-gnu &&
              npm i -g @napi-rs/cli@1.2.1 turbo@1.0.28 &&
              turbo run build-native --cache-dir=".turbo" -- --release --target aarch64-unknown-linux-gnu --zig --zig-abi-suffix 2.12 &&
              llvm-strip -x packages/toolpack/swc-source/native/shuvi-swc.*.node
          - host: ubuntu-18.04
            target: 'armv7-unknown-linux-gnueabihf'
            setup: |
              sudo apt-get update
              sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf -y
            build: |
              npm i -g @napi-rs/cli@1.2.1 turbo@1.0.28 &&
              turbo run build-native --cache-dir=".turbo" -- --release --target armv7-unknown-linux-gnueabihf
              arm-linux-gnueabihf-strip packages/toolpack/swc-source/native/shuvi-swc.*.node
          - host: ubuntu-latest
            target: 'aarch64-unknown-linux-musl'
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
            build: >-
              set -e &&
              npm i -g @napi-rs/cli@1.2.1 turbo@1.0.28 &&
              rustup toolchain install nightly-2021-08-12 &&
              rustup default nightly-2021-08-12 &&
              rustup target add aarch64-unknown-linux-musl &&
              turbo run build-native --cache-dir=".turbo" -- --release --target aarch64-unknown-linux-musl &&
              llvm-strip -x packages/toolpack/swc-source/native/shuvi-swc.*.node
          - host: windows-latest
            target: 'aarch64-pc-windows-msvc'
            build: |
              npm i -g @napi-rs/cli@1.2.1 turbo@1.0.28 &&
              turbo run build-native --cache-dir=".turbo" -- --release --target aarch64-pc-windows-msvc
    needs: testUnit
    name: stable - ${{ matrix.settings.target }} - node@16
    runs-on: ${{ matrix.settings.host }}
    steps:
      # https://github.com/actions/virtual-environments/issues/1187
      - name: tune linux network
        run: sudo ethtool -K eth0 tx off rx off
        if: ${{ matrix.settings.host == 'ubuntu-18.04' }}
      - name: tune linux network
        run: sudo ethtool -K eth0 tx off rx off
        if: ${{ matrix.settings.host == 'ubuntu-latest' }}
      - name: tune windows network
        run: Disable-NetAdapterChecksumOffload -Name * -TcpIPv4 -UdpIPv4 -TcpIPv6 -UdpIPv6
        if: ${{ matrix.settings.host == 'windows-latest' }}
      - name: tune mac network
        run: sudo sysctl -w net.link.generic.system.hwcksum_tx=0 && sudo sysctl -w net.link.generic.system.hwcksum_rx=0
        if: ${{ matrix.settings.host == 'macos-latest' }}
      # we use checkout here instead of the build cache since
      # it can fail to restore in different OS'
      - uses: actions/checkout@v2
      # We use restore-key to pick latest cache.
      # We will not get exact match, but doc says
      # "If there are multiple partial matches for a restore key, the action returns the most recently created cache."
      # So we get latest cache
      - name: Cache built files
        uses: actions/cache@v2
        with:
          path: packages/toolpack/target
          key: shuvi-swc-cargo-cache-${{ matrix.settings.target }}--${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            shuvi-swc-cargo-cache-${{ matrix.settings.target }}

      - name: Turbo Cache
       id: turbo-cache
       uses: actions/cache@v2
       with:
         path: .turbo
         key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ needs.build.outputs.weekNum }}-${{ github.sha }}
         restore-keys: |
           turbo-${{ github.job }}-
           turbo-${{ github.job }}-${{ github.ref_name }}-${{ needs.build.outputs.weekNum }}-
           turbo-${{ github.job }}-canary-${{ needs.build.outputs.weekNum }}-

      - name: Setup node
        uses: actions/setup-node@v2
        if: ${{ !matrix.settings.docker }}
        with:
          node-version: 16
          check-latest: true
          cache: yarn

      - name: Install
        uses: actions-rs/toolchain@v1
        if: ${{ !matrix.settings.docker }}
        with:
          profile: minimal
          override: true
          toolchain: nightly-2021-08-12
          target: ${{ matrix.settings.target }}

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ matrix.settings.target }}-cargo-registry

      - name: Cache cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: ${{ matrix.settings.target }}-cargo-index

      - name: Setup toolchain
        run: ${{ matrix.settings.setup }}
        if: ${{ matrix.settings.setup }}
        shell: bash

      - name: Build in docker
        uses: addnab/docker-run-action@v3
        if: ${{ matrix.settings.docker }}
        with:
          image: ${{ matrix.settings.docker }}
          options: -v ${{ env.HOME }}/.cargo/git:/root/.cargo/git -v ${{ env.HOME }}/.cargo/registry:/root/.cargo/registry -v ${{ github.workspace }}:/build -w /build
          run: ${{ matrix.settings.build }}

      - name: 'Build'
        run: ${{ matrix.settings.build }}
        if: ${{ !matrix.settings.docker }}
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: shuivi-swc-binaries
          path: packages/toolpack/swc-source/native/shuvi-swc.*.node


  publishRelease:
    name: Potentially publish release
    runs-on: ubuntu-latest
    needs:
      - buildNative
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      # https://github.com/actions/virtual-environments/issues/1187
      - name: tune linux network
        run: sudo ethtool -K eth0 tx off rx off

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - uses: actions/download-artifact@v2
        with:
          name: shuvi-swc-binaries
          path: packages/toolpack/swc-source/native

      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn install
      - run: node ./packages/toolpack/scripts/publish-native.js $GITHUB_REF
